#!/bin/bash -e


BUCKET=ec2-cache.binaris.com

# Requirements:
# - fzf
# - aws cli

function get_cache() {
    # Set you bucket name here
    aws s3 cp --quiet s3://$BUCKET/instances.fzf >(cat)
}

chosen=$(get_cache | fzf)

export key=$(echo $chosen | rev | cut -d ' ' -f1 | rev)
export ip=$(echo $chosen | rev | cut -d ' ' -f2 | rev)

ssh -i ~/.ssh/$key.pem ubuntu@$ip
